apiVersion: apps/v1
kind: StatefulSet  
metadata:
  name: sistema-noticias-stetefulset
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: sistema-noticias
  serviceName: svc-sistema-noticias
  template:
    metadata:
      labels:
        app: sistema-noticias
      name: sistema-noticias
    spec:
      containers:
        - name: sistema-noticias-container
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: sistema-configmap
